default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES: [ ]
  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: "study_python"
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  PORT: 8000
  HOST: "localhost"
  WEB_CONCURRENCY: 2


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2

heroku:
  HOST: "study-python-ariyaok.herokuapp.com"
