default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static/
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
    - src/application/blog/templates/
    - src/application/hello/templates/
    - src/application/landing/templates/

  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  PORT: 8000
  SECRET_KEY: "1"
  HOST: "localhost"
  WEB_CONCURRENCY: 2


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2

heroku:
  HOST: "study-python-ariyaok.herokuapp.com"
  MODE_DEBUG: false
  VENV_SYNTHETIC: true

