# Generated by Django 3.1.4 on 2020-12-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
