# Generated by Django 3.1.3 on 2020-12-01 17:34

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="crested_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="nr_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
