# Generated by Django 3.1.3 on 2020-12-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20201201_2034"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-crested_at"]},
        ),
    ]
